#!/bin/bash
#comentáio
echo "iniciando script"
echo "nome = input("Olá seja bem vindo, digite seu nome: ")"
echo "print(nome)"
echo "number1= float(input("Vamos calcular?\n" "Digite um número: "))"
echo "print(number1)"
echo "operacao= input("Digite a operação: ")"
echo "print(operacao)"
echo "number2= float(input("Digite outro número: "))"
echo "print(number1)"
echo "if operacao == "+":"
echo  	"resultado= number1 + number2"
echo  	"print(resultado)"
echo	"elif operacao == "-":"
echo 	"resultado= number1 - number2"
echo	"print(resultado)"
echo    "elif operacao == "*":"
echo	"resultado= number1 * number2"
echo	"print(resultado)"
echo	"elif operacao == "/":"
echo	"resultado= number1 / number2"
echo	"print(resultado)"
echo	"else"	
echo    "print("operação inválida")"
